#!/bin/sh
echo 'FRONTEND'
cat cdp_values.yaml | grep --color=always -A2 "registry.aggregion.com/dmp-frontend" | grep -v 'pullPolicy'
echo 'BACKEND'
cat cdp_values.yaml | grep --color=always -A2 "registry.aggregion.com/dmp-backend" | grep -v 'pullPolicy'
echo 'DATASERVICE-API'
cat cdp_values.yaml | grep --color=always -A2 "registry.aggregion.com/dataservice-api" | grep -v 'pullPolicy'
echo 'ATLAS-ENTITY-SYNCER'
cat cdp_values.yaml | grep --color=always -A2 "registry.aggregion.com/atlas-entity-syncer" | grep -v 'pullPolicy'
echo 'MEATADATA-SEED'
cat cdp_values.yaml | grep --color=always -A2 "registry.aggregion.com/metadata-seed" | grep -v 'pullPolicy'
echo 'ATLAS'
cat atlas_values.yaml | grep --color=always -A2 "aggregion/atlas" | grep -v 'pullPolicy'
echo 'TRINO'
cat trino_values.yaml | grep --color=always -A3 "registry.aggregion.com/trinodb/trino" | grep -v 'pullPolicy' | grep -v '#'
echo 'DATALAB-HASH'
cat cdp_values.yaml | grep 'datalab:'