{
 "title": "ClickHouse",
 "description": "ClickHouse internal exporter metrics",
 "tags": [
  "ClickHouse",
  "DB"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "DataSource", "query": "prometheus" },
   {
    "name": "instance",
    "label": "Node",
    "query": {
     "query": "label_values(ClickHouseAsyncMetrics_Uptime, instance)"
    }
   },
   { "name": "trends", "label": "Show trends", "query": "Yes : 1, No : null" },
   { "name": "peaks", "label": "Show peaks", "query": "Yes : 1, No : null" }
  ]
 },
 "panels": [
  {
   "title": "Nodes",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "ClickHouseMetrics_VersionInteger"
    },
    { "expr": "ClickHouseMetrics_Revision" },
    {
     "expr": "ClickHouseAsyncMetrics_NumberOfTables"
    },
    { "expr": "ClickHouseAsyncMetrics_Uptime" },
    {
     "expr": "ClickHouseAsyncMetrics_NumberOfDatabases"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "description": "Total amount of memory (bytes) allocated by the server.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "ClickHouseMetrics_MemoryTracking",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "description": "Number of connections to TCP server (clients with native interface), also included server-server distributed query connections. \nNumber of connections to HTTP server",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ClickHouseMetrics_TCPConnection",
     "legendFormat": "tcp - {{instance}}"
    },
    {
     "expr": "ClickHouseMetrics_HTTPConnection",
     "legendFormat": "http - {{instance}}"
    }
   ]
  },
  {
   "title": "Read backoff",
   "type": "graph",
   "description": "Number of times the number of query processing threads was lowered due to slow reads.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "expr": "max_over_time( (irate(ClickHouseProfileEvents_ReadBackoff{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
     "legendFormat": "peaks - {{instance}}"
    },
    {
     "expr": "rate(ClickHouseProfileEvents_ReadBackoff{instance=~\"$instance\"}[$__rate_interval]) * $trends",
     "legendFormat": "trend - {{instance}}"
    }
   ]
  },
  {
   "title": "Slow reads",
   "type": "graph",
   "description": "Number of reads from a file that were slow. This indicate system overload. Thresholds are controlled by read_backoff_* settings.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "expr": "max_over_time( (irate(ClickHouseProfileEvents_SlowRead{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
     "legendFormat": "peaks - {{instance}}"
    },
    {
     "expr": "rate(ClickHouseProfileEvents_SlowRead{instance=~\"$instance\"}[$__rate_interval]) * $trends",
     "legendFormat": "trend - {{instance}}"
    }
   ]
  },
  {
   "title": "Queries",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Queries",
     "type": "graph",
     "description": "Number of queries to be interpreted and potentially executed. Does not include queries that failed to parse or were rejected due to AST size limits, quota limits or limits on the number of simultaneously running queries. May include internal queries initiated by ClickHouse itself. Does not count subqueries.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_Query{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}"
      },
      {
       "expr": "rate(ClickHouseProfileEvents_Query{instance=~\"$instance\"}[$__rate_interval]) * $trends",
       "legendFormat": "trend - {{instance}}"
      }
     ]
    },
    {
     "title": "SELECT queries",
     "type": "graph",
     "description": "Same as Queries, but only for SELECT queries.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_SelectQuery{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}"
      },
      {
       "expr": "rate(ClickHouseProfileEvents_SelectQuery{instance=~\"$instance\"}[$__rate_interval]) * $trends",
       "legendFormat": "trend - {{instance}}"
      }
     ]
    },
    {
     "title": "INSERT queries",
     "type": "graph",
     "description": "Same as Queries, but only for INSERT queries.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_InsertQuery{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}"
      },
      {
       "expr": "rate(ClickHouseProfileEvents_InsertQuery{instance=~\"$instance\"}[$__rate_interval]) * $trends",
       "legendFormat": "trend - {{instance}}"
      }
     ]
    },
    {
     "title": "Failed SELECT queries",
     "type": "graph",
     "description": "Same as Failed queries, but only for SELECT queries.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_FailedSelectQuery{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}"
      },
      {
       "expr": "rate(ClickHouseProfileEvents_FailedSelectQuery{instance=~\"$instance\"}[$__rate_interval]) * $trends",
       "legendFormat": "trend - {{instance}}"
      }
     ]
    },
    {
     "title": "Failed queries",
     "type": "graph",
     "description": "Number of failed queries.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_FailedQuery{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}"
      },
      {
       "expr": "rate(ClickHouseProfileEvents_FailedQuery{instance=~\"$instance\"}[$__rate_interval]) * $trends",
       "legendFormat": "trend - {{instance}}"
      }
     ]
    },
    {
     "title": "Queries memory limit",
     "type": "graph",
     "description": "Number of times when memory limit exceeded for query.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_QueryMemoryLimitExceeded{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}"
      },
      {
       "expr": "rate(ClickHouseProfileEvents_QueryMemoryLimitExceeded{instance=~\"$instance\"}[$__rate_interval]) * $trends",
       "legendFormat": "trend - {{instance}}"
      }
     ]
    },
    {
     "title": "Query preemted",
     "type": "graph",
     "description": "Number of queries that are stopped and waiting due to 'priority' setting.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseMetrics_QueryPreempted{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}"
      },
      {
       "expr": "rate(ClickHouseMetrics_QueryPreempted{instance=~\"$instance\"}[$__rate_interval]) * $trends",
       "legendFormat": "trend - {{instance}}"
      }
     ]
    },
    {
     "title": "Failed INSERT queries",
     "type": "graph",
     "description": "Same as Failed queries, but only for INSERT queries.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_FailedInsertQuery{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}"
      },
      {
       "expr": "rate(ClickHouseProfileEvents_FailedInsertQuery{instance=~\"$instance\"}[$__rate_interval]) * $trends",
       "legendFormat": "trend - {{instance}}"
      }
     ]
    },
    {
     "title": "Query latencies (avg)",
     "type": "graph",
     "description": "Avg queries latencies",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "increase(ClickHouseProfileEvents_QueryTimeMicroseconds{instance=~\"$instance\"}[$__rate_interval]) / increase(ClickHouseProfileEvents_Query{instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "SELECT query latencies (avg)",
     "type": "graph",
     "description": "Avg SELECT queries latencies",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "increase(ClickHouseProfileEvents_SelectQueryTimeMicroseconds{instance=~\"$instance\"}[$__rate_interval]) / increase(ClickHouseProfileEvents_SelectQuery{instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "INSERT query latencies (avg)",
     "type": "graph",
     "description": "Avg INSERT queries latencies",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "increase(ClickHouseProfileEvents_InsertQueryTimeMicroseconds{instance=~\"$instance\"}[$__rate_interval]) / increase(ClickHouseProfileEvents_InsertQuery{instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Insert",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Inserted rows",
     "type": "graph",
     "description": "Number of rows INSERTed to all tables.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "cps" }
     ],
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_InsertedRows{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}"
      },
      {
       "expr": "rate(ClickHouseProfileEvents_InsertedRows{instance=~\"$instance\"}[$__rate_interval]) * $trends",
       "legendFormat": "trend - {{instance}}"
      }
     ]
    },
    {
     "title": "Inserted bytes",
     "type": "graph",
     "description": "Number of bytes (uncompressed; for columns as they stored in memory) INSERTed to all tables.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
     "yaxes": [
      { "format": "binBps" }
     ],
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_InsertedBytes{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}"
      },
      {
       "expr": "rate(ClickHouseProfileEvents_InsertedBytes{instance=~\"$instance\"}[$__rate_interval]) * $trends",
       "legendFormat": "trend - {{instance}}"
      }
     ]
    },
    {
     "title": "Delayed inserts",
     "type": "graph",
     "description": "Number of times the INSERT of a block to a MergeTree table was throttled due to high number of active data parts for partition.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
     "yaxes": [
      { "format": "cps" }
     ],
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_DelayedInserts{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}"
      },
      {
       "expr": "rate(ClickHouseProfileEvents_DelayedInserts{instance=~\"$instance\"}[$__rate_interval]) * $trends",
       "legendFormat": "trend - {{instance}}"
      }
     ]
    },
    {
     "title": "Rejected inserts",
     "type": "graph",
     "description": "Number of times the INSERT of a block to a MergeTree table was rejected with 'Too many parts' exception due to high number of active data parts for partition.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
     "yaxes": [
      { "format": "cps" }
     ],
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_RejectedInserts{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}"
      },
      {
       "expr": "rate(ClickHouseProfileEvents_RejectedInserts{instance=~\"$instance\"}[$__rate_interval]) * $trends",
       "legendFormat": "trend - {{instance}}"
      }
     ]
    },
    {
     "title": "Delayed inserts blocks (avg)",
     "type": "graph",
     "description": "Total number of milliseconds spent while the INSERT of a block to a MergeTree table was throttled due to high number of active data parts for partition.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "increase(ClickHouseProfileEvents_DelayedInsertsMilliseconds{instance=~\"$instance\"}[$__rate_interval]) / increase(ClickHouseProfileEvents_DelayedInserts{instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Select",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Parts",
     "type": "graph",
     "description": "Number of data parts selected to read from a MergeTree table.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "cps" }
     ],
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_SelectedParts{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}"
      },
      {
       "expr": "rate(ClickHouseProfileEvents_SelectedParts{instance=~\"$instance\"}[$__rate_interval]) * $trends",
       "legendFormat": "trend - {{instance}}"
      }
     ]
    },
    {
     "title": "Ranges",
     "type": "graph",
     "description": "Number of (non-adjacent) ranges in all data parts selected to read from a MergeTree table.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "yaxes": [
      { "format": "cps" }
     ],
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_SelectedRanges{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}"
      },
      {
       "expr": "rate(ClickHouseProfileEvents_SelectedRanges{instance=~\"$instance\"}[$__rate_interval]) * $trends",
       "legendFormat": "trend - {{instance}}"
      }
     ]
    },
    {
     "title": "Marks",
     "type": "graph",
     "description": "Number of marks (index granules) selected to read from a MergeTree table.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "cps" }
     ],
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_SelectedMarks{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}"
      },
      {
       "expr": "rate(ClickHouseProfileEvents_SelectedMarks{instance=~\"$instance\"}[$__rate_interval]) * $trends",
       "legendFormat": "trend - {{instance}}"
      }
     ]
    },
    {
     "title": "Rows",
     "type": "graph",
     "description": "Number of rows SELECTed from all tables.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
     "yaxes": [
      { "format": "cps" }
     ],
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_SelectedRows{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}"
      },
      {
       "expr": "rate(ClickHouseProfileEvents_SelectedRows{instance=~\"$instance\"}[$__rate_interval]) * $trends",
       "legendFormat": "trend - {{instance}}"
      }
     ]
    },
    {
     "title": "Bytes",
     "type": "graph",
     "description": "Number of bytes (uncompressed; for columns as they stored in memory) SELECTed from all tables.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
     "yaxes": [
      { "format": "binBps" }
     ],
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_SelectedBytes{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}"
      },
      {
       "expr": "rate(ClickHouseProfileEvents_SelectedBytes{instance=~\"$instance\"}[$__rate_interval]) * $trends",
       "legendFormat": "trend - {{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "IO",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "lseek",
     "type": "graph",
     "description": "Number of times the 'lseek' function was called.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_Seek{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}"
      },
      {
       "expr": "rate(ClickHouseProfileEvents_Seek{instance=~\"$instance\"}[$__rate_interval]) * $trends",
       "legendFormat": "trend - {{instance}}"
      }
     ]
    },
    {
     "title": "Open Files",
     "type": "graph",
     "description": "Number of files opened",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_FileOpen{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}"
      },
      {
       "expr": "rate(ClickHouseProfileEvents_FileOpen{instance=~\"$instance\"}[$__rate_interval]) * $trends",
       "legendFormat": "trend - {{instance}}"
      }
     ]
    },
    {
     "title": "Read from FD",
     "type": "graph",
     "description": "Number of reads (read/pread) from a file descriptor. Does not include sockets.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_ReadBufferFromFileDescriptorRead{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}"
      },
      {
       "expr": "rate(ClickHouseProfileEvents_ReadBufferFromFileDescriptorRead{instance=~\"$instance\"}[$__rate_interval]) * $trends",
       "legendFormat": "trend - {{instance}}"
      }
     ]
    },
    {
     "title": "Write to FD",
     "type": "graph",
     "description": "Number of writes (write/pwrite) to a file descriptor. Does not include sockets.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_WriteBufferFromFileDescriptorWrite{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}"
      },
      {
       "expr": "rate(ClickHouseProfileEvents_WriteBufferFromFileDescriptorWrite{instance=~\"$instance\"}[$__rate_interval]) * $trends",
       "legendFormat": "trend - {{instance}}"
      }
     ]
    },
    {
     "title": "Read from FD failed",
     "type": "graph",
     "description": "Number of times the read (read/pread) from a file descriptor have failed.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_ReadBufferFromFileDescriptorReadFailed{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}"
      },
      {
       "expr": "rate(ClickHouseProfileEvents_ReadBufferFromFileDescriptorReadFailed{instance=~\"$instance\"}[$__rate_interval]) * $trends",
       "legendFormat": "trend - {{instance}}"
      }
     ]
    },
    {
     "title": "Read from FD failed",
     "type": "graph",
     "description": "Number of times the read (read/pread) from a file descriptor have failed.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_ReadBufferFromFileDescriptorReadFailed{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}"
      },
      {
       "expr": "rate(ClickHouseProfileEvents_ReadBufferFromFileDescriptorReadFailed{instance=~\"$instance\"}[$__rate_interval]) * $trends",
       "legendFormat": "trend - {{instance}}"
      }
     ]
    },
    {
     "title": "Read bytes from FD",
     "type": "graph",
     "description": "Number of bytes read from file descriptors. If the file is compressed, this will show the compressed data size.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
     "yaxes": [
      { "format": "binBps" }
     ],
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_ReadBufferFromFileDescriptorReadBytes{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}"
      },
      {
       "expr": "rate(ClickHouseProfileEvents_ReadBufferFromFileDescriptorReadBytes{instance=~\"$instance\"}[$__rate_interval]) * $trends",
       "legendFormat": "trend - {{instance}}"
      }
     ]
    },
    {
     "title": "Write bytes to FD",
     "type": "graph",
     "description": "Number of bytes written to file descriptors. If the file is compressed, this will show compressed data size.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
     "yaxes": [
      { "format": "binBps" }
     ],
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_WriteBufferFromFileDescriptorWriteBytes{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}"
      },
      {
       "expr": "rate(ClickHouseProfileEvents_WriteBufferFromFileDescriptorWriteBytes{instance=~\"$instance\"}[$__rate_interval]) * $trends",
       "legendFormat": "trend - {{instance}}"
      }
     ]
    },
    {
     "title": "Read compressed bytes",
     "type": "graph",
     "description": "Number of bytes (the number of bytes before decompression) read from compressed sources (files, network).",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
     "yaxes": [
      { "format": "binBps" }
     ],
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_ReadCompressedBytes{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}"
      },
      {
       "expr": "rate(ClickHouseProfileEvents_ReadCompressedBytes{instance=~\"$instance\"}[$__rate_interval]) * $trends",
       "legendFormat": "trend - {{instance}}"
      }
     ]
    },
    {
     "title": "Read uncompressed bytes",
     "type": "graph",
     "description": "Number of uncompressed bytes (the number of bytes after decompression) read from compressed sources (files, network).",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 65 },
     "yaxes": [
      { "format": "binBps" }
     ],
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_CompressedReadBufferBytes{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}"
      },
      {
       "expr": "rate(ClickHouseProfileEvents_CompressedReadBufferBytes{instance=~\"$instance\"}[$__rate_interval]) * $trends",
       "legendFormat": "trend - {{instance}}"
      }
     ]
    },
    {
     "title": "Compressed blocks",
     "type": "graph",
     "description": "Number of compressed blocks (the blocks of data that are compressed independent of each other) read from compressed sources (files, network).",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 73 },
     "yaxes": [
      { "format": "cps" }
     ],
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_CompressedReadBufferBlocks{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}"
      },
      {
       "expr": "rate(ClickHouseProfileEvents_CompressedReadBufferBlocks{instance=~\"$instance\"}[$__rate_interval]) * $trends",
       "legendFormat": "trend - {{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Replicas",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Readonly replica",
     "type": "graph",
     "description": "Number of Replicated tables that are currently in readonly state due to re-initialization after ZooKeeper session loss or due to startup without ZooKeeper configured.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "ClickHouseMetrics_ReadonlyReplica",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Replicated part failed fetches",
     "type": "graph",
     "description": "Number of times a data part was failed to download from replica of a ReplicatedMergeTree table.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
     "yaxes": [
      { "format": "cps" }
     ],
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_ReplicatedPartFailedFetches{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}"
      },
      {
       "expr": "rate(ClickHouseProfileEvents_ReplicatedPartFailedFetches{instance=~\"$instance\"}[$__rate_interval]) * $trends",
       "legendFormat": "trend - {{instance}}"
      }
     ]
    },
    {
     "title": "Replicated part fetches",
     "type": "graph",
     "description": "Number of times a data part was downloaded from replica of a ReplicatedMergeTree table.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
     "yaxes": [
      { "format": "cps" }
     ],
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_ReplicatedPartFetches{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}"
      },
      {
       "expr": "rate(ClickHouseProfileEvents_ReplicatedPartFetches{instance=~\"$instance\"}[$__rate_interval]) * $trends",
       "legendFormat": "trend - {{instance}}"
      }
     ]
    },
    {
     "title": "Replicated part fetches or merges",
     "type": "graph",
     "description": "Number of times we prefer to download already merged part from replica of ReplicatedMergeTree table instead of performing a merge ourself (usually we prefer doing a merge ourself to save network traffic). This happens when we have not all source parts to perform a merge or when the data part is old enough.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
     "yaxes": [
      { "format": "cps" }
     ],
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_ReplicatedPartFetchesOfMerged{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}"
      },
      {
       "expr": "rate(ClickHouseProfileEvents_ReplicatedPartFetchesOfMerged{instance=~\"$instance\"}[$__rate_interval]) * $trends",
       "legendFormat": "trend - {{instance}}"
      }
     ]
    },
    {
     "title": "Replicated part merges",
     "type": "graph",
     "description": "Number of times data parts of ReplicatedMergeTree tables were successfully merged.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
     "yaxes": [
      { "format": "cps" }
     ],
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_ReplicatedPartMerges{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}"
      },
      {
       "expr": "rate(ClickHouseProfileEvents_ReplicatedPartMerges{instance=~\"$instance\"}[$__rate_interval]) * $trends",
       "legendFormat": "trend - {{instance}}"
      }
     ]
    },
    {
     "title": "Replicated part data loss",
     "type": "graph",
     "description": "Number of times a data part that we wanted doesn't exist on any replica (even on replicas that are offline right now). That data parts are definitely lost. This is normal due to asynchronous replication (if quorum inserts were not enabled), when the replica on which the data part was written was failed and when it became online after fail it doesn't contain that data part.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
     "yaxes": [
      { "format": "cps" }
     ],
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_ReplicatedDataLoss{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}"
      },
      {
       "expr": "rate(ClickHouseProfileEvents_ReplicatedDataLoss{instance=~\"$instance\"}[$__rate_interval]) * $trends",
       "legendFormat": "trend - {{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Merge",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Merge",
     "type": "graph",
     "description": "Number of launched background merges.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "cps" }
     ],
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_Merge{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}"
      },
      {
       "expr": "rate(ClickHouseProfileEvents_Merge{instance=~\"$instance\"}[$__rate_interval]) * $trends",
       "legendFormat": "trend - {{instance}}"
      }
     ]
    },
    {
     "title": "Merged rows",
     "type": "graph",
     "description": "Rows read for background merges. This is the number of rows before merge.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
     "yaxes": [
      { "format": "cps" }
     ],
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_MergedRows{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}"
      },
      {
       "expr": "rate(ClickHouseProfileEvents_MergedRows{instance=~\"$instance\"}[$__rate_interval]) * $trends",
       "legendFormat": "trend - {{instance}}"
      }
     ]
    },
    {
     "title": "Merge uncompressed bytes",
     "type": "graph",
     "description": "Uncompressed bytes (for columns as they stored in memory) that was read for background merges. This is the number before merge.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
     "yaxes": [
      { "format": "binBps" }
     ],
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_MergedUncompressedBytes{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}"
      },
      {
       "expr": "rate(ClickHouseProfileEvents_MergedUncompressedBytes{instance=~\"$instance\"}[$__rate_interval]) * $trends",
       "legendFormat": "trend - {{instance}}"
      }
     ]
    },
    {
     "title": "Merge duration (avg)",
     "type": "graph",
     "description": "Avg merge duration",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "increase(ClickHouseProfileEvents_MergesTimeMilliseconds{instance=~\"$instance\"}[$__rate_interval]) / increase(ClickHouseProfileEvents_Merge{instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "MergeTree rows",
     "type": "graph",
     "description": "Number of rows INSERTed to MergeTree tables.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
     "yaxes": [
      { "format": "cps" }
     ],
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_MergeTreeDataWriterRows{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}"
      },
      {
       "expr": "rate(ClickHouseProfileEvents_MergeTreeDataWriterRows{instance=~\"$instance\"}[$__rate_interval]) * $trends",
       "legendFormat": "trend - {{instance}}"
      }
     ]
    },
    {
     "title": "MergeTree blocks",
     "type": "graph",
     "description": "Number of blocks INSERTed to MergeTree tables. Each block forms a data part of level zero.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
     "yaxes": [
      { "format": "cps" }
     ],
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_MergeTreeDataWriterBlocks{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}"
      },
      {
       "expr": "rate(ClickHouseProfileEvents_MergeTreeDataWriterBlocks{instance=~\"$instance\"}[$__rate_interval]) * $trends",
       "legendFormat": "trend - {{instance}}"
      }
     ]
    },
    {
     "title": "MergeTree uncompressed bytes",
     "type": "graph",
     "description": "Uncompressed bytes (for columns as they stored in memory) INSERTed to MergeTree tables.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
     "yaxes": [
      { "format": "binBps" }
     ],
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_MergeTreeDataWriterUncompressedBytes{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}"
      },
      {
       "expr": "rate(ClickHouseProfileEvents_MergeTreeDataWriterUncompressedBytes{instance=~\"$instance\"}[$__rate_interval]) * $trends",
       "legendFormat": "trend - {{instance}}"
      }
     ]
    },
    {
     "title": "MergeTree compressed bytes",
     "type": "graph",
     "description": "Bytes written to filesystem for data INSERTed to MergeTree tables.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
     "yaxes": [
      { "format": "binBps" }
     ],
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_MergeTreeDataWriterCompressedBytes{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}"
      },
      {
       "expr": "rate(ClickHouseProfileEvents_MergeTreeDataWriterCompressedBytes{instance=~\"$instance\"}[$__rate_interval]) * $trends",
       "legendFormat": "trend - {{instance}}"
      }
     ]
    },
    {
     "title": "Reserved space",
     "type": "graph",
     "description": "Disk space reserved for currently running background merges. It is slightly more than the total size of currently merging parts.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "ClickHouseMetrics_DiskSpaceReservedForMerge",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Cache",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Uncompressed Cache Hits",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_UncompressedCacheHits{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}"
      },
      {
       "expr": "rate(ClickHouseProfileEvents_UncompressedCacheHits{instance=~\"$instance\"}[$__rate_interval]) * $trends",
       "legendFormat": "trend - {{instance}}"
      }
     ]
    },
    {
     "title": "Uncompressed Cache Misses",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_UncompressedCacheMisses{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}"
      },
      {
       "expr": "rate(ClickHouseProfileEvents_UncompressedCacheMisses{instance=~\"$instance\"}[$__rate_interval]) * $trends",
       "legendFormat": "trend - {{instance}}"
      }
     ]
    },
    {
     "title": "Mark Cache Hits",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_MarkCacheHits{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}"
      },
      {
       "expr": "rate(ClickHouseProfileEvents_MarkCacheHits{instance=~\"$instance\"}[$__rate_interval]) * $trends",
       "legendFormat": "trend - {{instance}}"
      }
     ]
    },
    {
     "title": "Mark Cache Misses",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_MarkCacheMisses{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}"
      },
      {
       "expr": "rate(ClickHouseProfileEvents_MarkCacheMisses{instance=~\"$instance\"}[$__rate_interval]) * $trends",
       "legendFormat": "trend - {{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Parts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Temporary",
     "type": "graph",
     "description": "The part is generating now, it is not in data_parts list.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "ClickHouseMetrics_PartsTemporary",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Pre commited",
     "type": "graph",
     "description": "The part is in data_parts, but not used for SELECTs.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "ClickHouseMetrics_PartsPreCommitted",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Commited",
     "type": "graph",
     "description": "The part is in data_parts, but not used for SELECTs.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "ClickHouseMetrics_PartsCommitted",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Outdated",
     "type": "graph",
     "description": "Not active data part, but could be used by only current SELECTs, could be deleted after SELECTs finishes.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "ClickHouseMetrics_PartsOutdated",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Deleting",
     "type": "graph",
     "description": "Not active data part with identity refcounter, it is deleting right now by a cleaner.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "ClickHouseMetrics_PartsDeleting",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Delete on destroy",
     "type": "graph",
     "description": "Part was moved to another disk and should be deleted in own destructor.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "ClickHouseMetrics_PartsDeleteOnDestroy",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Wide",
     "type": "graph",
     "description": "Wide parts.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "ClickHouseMetrics_PartsWide", "legendFormat": "{{instance}}" }
     ]
    },
    {
     "title": "Compact",
     "type": "graph",
     "description": "Compact parts.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "ClickHouseMetrics_PartsCompact", "legendFormat": "{{instance}}" }
     ]
    },
    {
     "title": "In-memory",
     "type": "graph",
     "description": "In-memory parts.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "ClickHouseMetrics_PartsInMemory",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Distributed",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Send",
     "type": "graph",
     "description": "Number of connections to remote servers sending data that was INSERTed into Distributed tables. Both synchronous and asynchronous mode.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "ClickHouseMetrics_DistributedSend",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Files to insert",
     "type": "graph",
     "description": "Number of pending files to process for asynchronous insertion into Distributed tables. Number of files for every shard is summed.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "ClickHouseMetrics_DistributedFilesToInsert",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Distributed delayed inserts",
     "type": "graph",
     "description": "Number of times the INSERT of a block to a Distributed table was throttled due to high number of pending bytes.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_DistributedDelayedInserts{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}"
      },
      {
       "expr": "rate(ClickHouseProfileEvents_DistributedDelayedInserts{instance=~\"$instance\"}[$__rate_interval]) * $trends",
       "legendFormat": "trend - {{instance}}"
      }
     ]
    },
    {
     "title": "Distributed rejected inserts",
     "type": "graph",
     "description": "Number of times the INSERT of a block to a Distributed table was rejected with 'Too many bytes' exception due to high number of pending bytes.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_DistributedRejectedInserts{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}"
      },
      {
       "expr": "rate(ClickHouseProfileEvents_DistributedRejectedInserts{instance=~\"$instance\"}[$__rate_interval]) * $trends",
       "legendFormat": "trend - {{instance}}"
      }
     ]
    },
    {
     "title": "Distributed delayed inserts blocks (avg)",
     "type": "graph",
     "description": "Total number of milliseconds spent while the INSERT of a block to a Distributed table was throttled due to high number of pending bytes.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "increase(ClickHouseProfileEvents_DistributedDelayedInsertsMilliseconds{instance=~\"$instance\"}[$__rate_interval]) / increase(ClickHouseProfileEvents_DistributedDelayedInserts{instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Distributed connection fail try",
     "type": "graph",
     "description": "Total count when distributed connection fails with retry",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_DistributedConnectionFailTry{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}"
      },
      {
       "expr": "rate(ClickHouseProfileEvents_DistributedConnectionFailTry{instance=~\"$instance\"}[$__rate_interval]) * $trends",
       "legendFormat": "trend - {{instance}}"
      }
     ]
    },
    {
     "title": "Distributed connection fail at all",
     "type": "graph",
     "description": "Total count when distributed connection fails after all retries finished",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_DistributedConnectionFailAtAll{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}"
      },
      {
       "expr": "rate(ClickHouseProfileEvents_DistributedConnectionFailAtAll{instance=~\"$instance\"}[$__rate_interval]) * $trends",
       "legendFormat": "trend - {{instance}}"
      }
     ]
    },
    {
     "title": "Distributed sync insertation timeout",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_DistributedSyncInsertionTimeoutExceeded{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}"
      },
      {
       "expr": "rate(ClickHouseProfileEvents_DistributedSyncInsertionTimeoutExceeded{instance=~\"$instance\"}[$__rate_interval]) * $trends",
       "legendFormat": "trend - {{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Background pool",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "BackgroundPool task",
     "type": "graph",
     "description": "Number of active tasks in BackgroundProcessingPool (merges, mutations, or replication queue bookkeeping)",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "ClickHouseMetrics_BackgroundPoolTask",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "BackgroundFetchesPool task",
     "type": "graph",
     "description": "Number of active tasks in BackgroundFetchesPool",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "ClickHouseMetrics_BackgroundFetchesPoolTask",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "BackgroundMovePool task",
     "type": "graph",
     "description": "Number of active tasks in BackgroundProcessingPool for moves",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "ClickHouseMetrics_BackgroundMovePoolTask",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "BackgroundSchedulePool task",
     "type": "graph",
     "description": "Number of active tasks in BackgroundSchedulePool. This pool is used for periodic ReplicatedMergeTree tasks, like cleaning old data parts, altering data parts, replica re-initialization, etc.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "ClickHouseMetrics_BackgroundSchedulePoolTask",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "BackgroundBufferFlushSchedulePool task",
     "type": "graph",
     "description": "Number of active tasks in BackgroundBufferFlushSchedulePool. This pool is used for periodic Buffer flushes",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "ClickHouseMetrics_BackgroundBufferFlushSchedulePoolTask",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "BackgroundDistributedSchedulePool task",
     "type": "graph",
     "description": "Number of active tasks in BackgroundDistributedSchedulePool. This pool is used for distributed sends that is done in background.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "ClickHouseMetrics_BackgroundDistributedSchedulePoolTask",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "BackgroundMessageBrokerSchedulePool task",
     "type": "graph",
     "description": "Number of active tasks in BackgroundProcessingPool for message streaming",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "ClickHouseMetrics_BackgroundMessageBrokerSchedulePoolTask",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Zookeeper",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "Init",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_ZooKeeperInit{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}"
      },
      {
       "expr": "rate(ClickHouseProfileEvents_ZooKeeperInit{instance=~\"$instance\"}[$__rate_interval]) * $trends",
       "legendFormat": "trend - {{instance}}"
      }
     ]
    },
    {
     "title": "Transactions",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_ZooKeeperTransactions{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}"
      },
      {
       "expr": "rate(ClickHouseProfileEvents_ZooKeeperTransactions{instance=~\"$instance\"}[$__rate_interval]) * $trends",
       "legendFormat": "trend - {{instance}}"
      }
     ]
    },
    {
     "title": "List",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_ZooKeeperList{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}"
      },
      {
       "expr": "rate(ClickHouseProfileEvents_ZooKeeperList{instance=~\"$instance\"}[$__rate_interval]) * $trends",
       "legendFormat": "trend - {{instance}}"
      }
     ]
    },
    {
     "title": "Create",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_ZooKeeperCreate{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}"
      },
      {
       "expr": "rate(ClickHouseProfileEvents_ZooKeeperCreate{instance=~\"$instance\"}[$__rate_interval]) * $trends",
       "legendFormat": "trend - {{instance}}"
      }
     ]
    },
    {
     "title": "Remove",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_ZooKeeperRemove{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}"
      },
      {
       "expr": "rate(ClickHouseProfileEvents_ZooKeeperRemove{instance=~\"$instance\"}[$__rate_interval]) * $trends",
       "legendFormat": "trend - {{instance}}"
      }
     ]
    },
    {
     "title": "Exists",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_ZooKeeperExists{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}"
      },
      {
       "expr": "rate(ClickHouseProfileEvents_ZooKeeperExists{instance=~\"$instance\"}[$__rate_interval]) * $trends",
       "legendFormat": "trend - {{instance}}"
      }
     ]
    },
    {
     "title": "Get",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_ZooKeeperGet{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}"
      },
      {
       "expr": "rate(ClickHouseProfileEvents_ZooKeeperGet{instance=~\"$instance\"}[$__rate_interval]) * $trends",
       "legendFormat": "trend - {{instance}}"
      }
     ]
    },
    {
     "title": "Set",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_ZooKeeperSet{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}"
      },
      {
       "expr": "rate(ClickHouseProfileEvents_ZooKeeperSet{instance=~\"$instance\"}[$__rate_interval]) * $trends",
       "legendFormat": "trend - {{instance}}"
      }
     ]
    },
    {
     "title": "Multi",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_ZooKeeperMulti{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}"
      },
      {
       "expr": "rate(ClickHouseProfileEvents_ZooKeeperMulti{instance=~\"$instance\"}[$__rate_interval]) * $trends",
       "legendFormat": "trend - {{instance}}"
      }
     ]
    },
    {
     "title": "Check",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 61 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_ZooKeeperCheck{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}"
      },
      {
       "expr": "rate(ClickHouseProfileEvents_ZooKeeperCheck{instance=~\"$instance\"}[$__rate_interval]) * $trends",
       "legendFormat": "trend - {{instance}}"
      }
     ]
    },
    {
     "title": "Close",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 69 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_ZooKeeperClose{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}"
      },
      {
       "expr": "rate(ClickHouseProfileEvents_ZooKeeperClose{instance=~\"$instance\"}[$__rate_interval]) * $trends",
       "legendFormat": "trend - {{instance}}"
      }
     ]
    },
    {
     "title": "Watch response",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 69 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_ZooKeeperWatchResponse{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}"
      },
      {
       "expr": "rate(ClickHouseProfileEvents_ZooKeeperWatchResponse{instance=~\"$instance\"}[$__rate_interval]) * $trends",
       "legendFormat": "trend - {{instance}}"
      }
     ]
    },
    {
     "title": "User Exceptions",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 77 },
     "yaxes": [
      { "format": "cps" }
     ],
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_ZooKeeperUserExceptions{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}"
      },
      {
       "expr": "rate(ClickHouseProfileEvents_ZooKeeperUserExceptions{instance=~\"$instance\"}[$__rate_interval]) * $trends",
       "legendFormat": "trend - {{instance}}"
      }
     ]
    },
    {
     "title": "Hardware Exceptions",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 77 },
     "yaxes": [
      { "format": "cps" }
     ],
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_ZooKeeperHardwareExceptions{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}"
      },
      {
       "expr": "rate(ClickHouseProfileEvents_ZooKeeperHardwareExceptions{instance=~\"$instance\"}[$__rate_interval]) * $trends",
       "legendFormat": "trend - {{instance}}"
      }
     ]
    },
    {
     "title": "Bytes received",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 85 },
     "yaxes": [
      { "format": "binBps" }
     ],
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_ZooKeeperBytesReceived{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}"
      },
      {
       "expr": "rate(ClickHouseProfileEvents_ZooKeeperBytesReceived{instance=~\"$instance\"}[$__rate_interval]) * $trends",
       "legendFormat": "trend - {{instance}}"
      }
     ]
    },
    {
     "title": "Bytes sent",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 85 },
     "yaxes": [
      { "format": "binBps" }
     ],
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_ZooKeeperBytesSent{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}"
      },
      {
       "expr": "rate(ClickHouseProfileEvents_ZooKeeperBytesSent{instance=~\"$instance\"}[$__rate_interval]) * $trends",
       "legendFormat": "trend - {{instance}}"
      }
     ]
    },
    {
     "title": "Sessions",
     "type": "graph",
     "description": "Number of sessions (connections) to ZooKeeper. Should be no more than one, because using more than one connection to ZooKeeper may lead to bugs due to lack of linearizability (stale reads) that ZooKeeper consistency model allows.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 93 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "ClickHouseMetrics_ZooKeeperSession",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Ephemeral Node",
     "type": "graph",
     "description": "Number of ephemeral nodes hold in ZooKeeper.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 93 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "ClickHouseMetrics_EphemeralNode",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Watches",
     "type": "graph",
     "description": "Number of watches (event subscriptions) in ZooKeeper.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 101 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "ClickHouseMetrics_ZooKeeperWatch",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Requests",
     "type": "graph",
     "description": "Number of requests to ZooKeeper in fly.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 101 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "ClickHouseMetrics_ZooKeeperRequest",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Remove ephemeral node failed",
     "type": "graph",
     "description": "Number of times an error happened while trying to remove ephemeral node. This is not an issue, because our implementation of ZooKeeper library guarantee that the session will expire and the node will be removed.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 109 },
     "yaxes": [
      { "format": "cps" }
     ],
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_CannotRemoveEphemeralNode{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}"
      },
      {
       "expr": "rate(ClickHouseProfileEvents_CannotRemoveEphemeralNode{instance=~\"$instance\"}[$__rate_interval]) * $trends",
       "legendFormat": "trend - {{instance}}"
      }
     ]
    }
   ]
  }
 ]
}