{
 "title": "Enclave monitoring",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "enclave endpoints [  probe_http_duration ]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "probe_http_duration_seconds{job=\"enclave\"}",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "enclave endpoints [ TCP : 8888 ]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "probe_duration_seconds{job=\"enclave_tcp\", target=~\".*:8888\"}",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "enclave endpoints [ TCP : 18765 ]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "probe_duration_seconds{job=\"enclave_tcp\", target=~\".*:18765\"}",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "enclave endpoints [ TCP : 9011 ]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "probe_duration_seconds{job=\"enclave_tcp\", target=~\".*:9011\"}",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "enclave endpoints [ TCP : 443 ]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "probe_duration_seconds{job=\"enclave_tcp\", target=~\".*:443\"}",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "enclave endpoints [ ICMP ]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "probe_duration_seconds{job=\"enclave_icmp\"}",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "enclave endpoints [ TCP : 8081 ]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "probe_duration_seconds{job=\"enclave_tcp\", target=~\".*:8081\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}