{
 "title": "SGX",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "sgx_loaded_back",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "sgx_loaded_back", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": "sgx_init_enclaves",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "sgx_init_enclaves", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": "sgx_nr_added_pages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "sgx_nr_added_pages", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": "sgx_nr_evicted",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "sgx_nr_evicted", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": " sgx_nr_alloc_pages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "sgx_nr_alloc_pages", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": "sgx_nr_epc_sections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    { "expr": "sgx_nr_epc_sections", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": "sgx_nr_enclaves",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    { "expr": "sgx_nr_enclaves", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": "nr_free_pages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    { "expr": "sgx_nr_free_pages", "legendFormat": "{{__name__}}" }
   ]
  }
 ]
}